name: portfolio
description: My porfolio website.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lacquer
      fonts:
        - asset: assets/fonts/Lacquer-Regular.ttf
#         style: italic
    - family: Londrina Outline
      fonts:
        - asset: assets/fonts/LondrinaOutline-Regular.ttf
#         weight: 700


